on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

name: CI

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  nightly: nightly-2020-09-21
  minrust: 1.45.2

jobs:
  # Depends on all action sthat are required for a "successful" CI run.
  tests-pass:
    name: all systems go
    runs-on: ubuntu-latest
    needs:
      - test
      - test-unstable
      - miri
      - cross
      - features
      - minrust
      - fmt
      - clippy
      - docs
      - loom
    steps:
      - run: exit 0

  test:
    name: test tokio full
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-hack
        run: cargo install cargo-hack

      # Run `tokio` with `full` features. This excludes testing utilities which
      # can alter the runtime behavior of Tokio.
      - name: test tokio full
        run: cargo test --features full
        working-directory: tokio

      # Test **all** crates in the workspace with all features.
      - name: test all --all-features
        run: cargo test --workspace --all-features

      # Run integration tests for each feature
      - name: test tests-integration --each-feature
        run: cargo hack test --each-feature
        working-directory: tests-integration

      # Run macro build tests
      - name: test tests-build --each-feature
        run: cargo hack test --each-feature
        working-directory: tests-build

  test-unstable:
    name: test tokio full --unstable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable

      # Run `tokio` with "unstable" cfg flag.
      - name: test tokio full --cfg unstable
        run: cargo test --features full
        working-directory: tokio
        env:
          RUSTFLAGS: --cfg tokio_unstable -Dwarnings

  miri:
    name: miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          override: true
      - name: Install Miri
        run: |
          set -e
          rustup component add miri
          cargo miri setup
          rm -rf tokio/tests

      - name: miri
        run: cargo miri test --features rt,rt-multi-thread,sync task
        working-directory: tokio
  san:
    name: san
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          override: true
      - name: asan
        run: cargo test --all-features --target x86_64-unknown-linux-gnu --lib -- --test-threads 1
        working-directory: tokio
        env:
          RUSTFLAGS: -Z sanitizer=address
          ASAN_OPTIONS: detect_leaks=0

  cross:
    name: cross
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
          - target: powerpc-unknown-linux-gnu
            os: ubuntu-latest
          - target: powerpc64-unknown-linux-gnu
            os: ubuntu-latest
            subcmd: check # cross does not provide a Docker image for powerpc64-unknown-linux-gnu
          - target: mips-unknown-linux-gnu
            os: ubuntu-latest
          - target: arm-linux-androideabi
            os: ubuntu-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            subcmd: build # cross does not provide a Docker image for aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: cross --target ${{ matrix.target }}
        run: |
          cargo install cross
          cross ${{ matrix.subcmd || 'test' }} --workspace --all-features --target ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')
      - name: cargo --target ${{ matrix.target }}
        run: |
          rustup target add ${{ matrix.target }}
          cargo ${{ matrix.subcmd || 'test' }} --workspace --all-features --target ${{ matrix.target }}
        if: startsWith(matrix.os, 'windows')

  features:
    name: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          override: true
      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: check --each-feature
        run: cargo hack check --all --each-feature -Z avoid-dev-deps

      # Try with unstable feature flags
      - name: check --each-feature --unstable
        run: cargo hack check --all --each-feature -Z avoid-dev-deps
        env:
          RUSTFLAGS: --cfg tokio_unstable -Dwarnings

  minrust:
    name: minrust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.minrust }}
          override: true

      - name: "test --workspace --all-features"
        run: cargo check --workspace --all-features

  minimal-versions:
    name: minimal-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          override: true
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - name: "check --all-features -Z minimal-versions"
        run: |
          # Remove dev-dependencies from Cargo.toml to prevent the next `cargo update`
          # from determining minimal versions based on dev-dependencies.
          cargo hack --remove-dev-deps --workspace
          # Update Cargo.lock to minimal version dependencies.
          cargo update -Z minimal-versions
          cargo check --all-features

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - name: Install rustfmt
        run: rustup component add rustfmt

      # Check fmt
      - name: "rustfmt --check"
        # Workaround for rust-lang/cargo#7732
        run: |
          if ! rustfmt --check --edition 2018 $(find . -name '*.rs' -print); then
            printf "Please run \`rustfmt --edition 2018 \$(find . -name '*.rs' -print)\` to fix rustfmt errors.\nSee CONTRIBUTING.md for more details.\n" >&2
            exit 1
          fi

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update ${{ env.minrust }} && rustup default ${{ env.minrust }}
      - name: Install clippy
        run: rustup component add clippy

      # Run clippy
      - name: "clippy --all"
        run: cargo clippy --all --tests --all-features

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          override: true

      - name: "doc --lib --all-features"
        run: cargo doc --lib --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs

  loom:
    name: loom
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scope:
          - --skip loom_pool
          - loom_pool::group_a
          - loom_pool::group_b
          - loom_pool::group_c
          - loom_pool::group_d
          - time::driver
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable

      - name: loom ${{ matrix.scope }}
        run: cargo test --lib --release --features full -- --nocapture $SCOPE
        working-directory: tokio
        env:
          RUSTFLAGS: --cfg loom --cfg tokio_unstable -Dwarnings
          LOOM_MAX_PREEMPTIONS: 2
          SCOPE: ${{ matrix.scope }}
